### PR TITLE
Stop using deprected functions (opaleye 0.7)

### PR DESCRIPTION
**Pull request by Arguggi**
Also bump upper bound on opaleye and stackage nightly

### CODE REVIEW

**Review by wraithm — APPROVED** [review]

**Comment by wraithm** [comment]
Thanks!

**Comment by wraithm** [comment]
I actually just noticed this yesterday 👍

**Comment by wraithm** [comment]
I'll upload this to hackage later this afternoon.

**Comment by Arguggi** [comment]
Thanks!

**Comment by wraithm** [comment]
@Arguggi opaleye-trans 0.3.7 is uploaded to hackage.

**Comment by wraithm** [comment]
@Arguggi While I have your attention and just letting you know, I'm working on the next version of `opaleye-trans`. I'm adding some error handling to `Transaction`. Let me know what your thoughts are. I was thinking that I'd just make `Transaction` have an `ExceptT String` in its stack, and when you run a transaction, it could possibly fail when you run it.

**Comment by Arguggi** [comment]
That was really quick, thanks again! Keep in mind I don't really have much experience with sql / databases so I don't know how valuable my input is. That being said, I guess an `ExceptT String` is fine. 

But since `opaleye` uses  `postgresql-simple` under the hood and that library throws (according to the documentation of [query](http://hackage.haskell.org/package/postgresql-simple-0.5.3.0/docs/Database-PostgreSQL-Simple.html#v:query)):

   - `FormatError`: Shouldn't be possible with `opaleye`?
   - `QueryError`:  Shouldn't be possible with `opaleye`?
   - `ResultError`: Shouldn't be possible with `opaleye`?
   - `SqlError`: Possible

maybe catching only `SqlError`s and adding a `ExceptT SqlError` is better?

**Comment by wraithm** [comment]
Just pushed `0.4.0` with a new module for exception handling. I also removed `MonadBase` instances. I really didn't enjoy the fact that this stuff brought in `UndecidableInstances`.

**Pull request merged**
